- .github/workflows/ci.yml
- .gitignore
- Makefile
- Stdlib/Data/Bool.mjuvix
- Stdlib/Data/List.mjuvix
- Stdlib/Data/Maybe.mjuvix
- Stdlib/Data/Nat.mjuvix
- Stdlib/Data/Nat/Ord.mjuvix
- Stdlib/Data/Ord.mjuvix
- Stdlib/Data/String.mjuvix
- Stdlib/Data/String/Ord.mjuvix
- Stdlib/Prelude.mjuvix
- Stdlib/System/IO.mjuvix
- index.mjuvix
This PR should be merged after https://github.com/heliaxdev/minijuvix-stdlib/pull/4
Pass the `--no-stdlib` flag when typechecking and building the HTML output.
> Update stdlib to support minijuvix examples

- Stdlib/Data/List.juvix
Temporary fix for Juvix issue [#1382](https://github.com/anoma/juvix/issues/1382). Fixing Juvix issue [#1341](https://github.com/anoma/juvix/issues/1341) depends on this.
> Remove quickSort

- Stdlib/Data/Nat.juvix
- Stdlib/Data/String/Ord.juvix
We don't want to include an `Int` type in the standard library before we have support for arbitrary precision numbers https://github.com/anoma/juvix/issues/1356
The `SimpleFungibleToken` example juvix program requires an Int type - we will include it inside that project for now.
This PR also fixes the `eqString` axiom which had an incorrect compile block reference.
> Remove Int type

- Stdlib/Data/Bool.juvix
- Stdlib/Data/List.juvix
- Stdlib/Data/Maybe.juvix
- Stdlib/Data/Nat.juvix
- Stdlib/Data/Nat/Ord.juvix
- Stdlib/Data/Product.juvix
- Stdlib/Data/String/Ord.juvix
- Stdlib/Function.juvix
- Stdlib/System/IO.juvix
merge after #14. Solves https://github.com/anoma/juvix/issues/1465 in the standard library
> Rplace ≔ by :=

- .github/workflows/ci.yml
The Juvix build depends on LLVM tools for building the runtime.
This is the reason why CI is currently failing for PRs: https://github.com/anoma/juvix-stdlib/actions/runs/3592093350/jobs/6047401613
> CI: Install LLVM before build

- .github/workflows/ci.yml
There's an issue with libtinfo5 not being available on ubuntu-22.04.
This also bumps the haskell action ghc version to 9.2.5, though ghc is installed by stack.
> Pin CI OS to ubuntu-20.04

- Stdlib/Data/String.juvix
- Stdlib/System/IO.juvix
The juvix repo points to a revision of juvix-stdlib that contains these commits. I somehow forgot to PR this.
> Make String a builtin and add print* variants with terminating newlines

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitignore
- readme.md
- readme.org
[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=455254004)
> Add codespaces

- Stdlib/Data/Nat.juvix
- Stdlib/Data/Nat/Gcd.juvix
- Stdlib/System/IO.juvix
The GCD in the standard library was inefficient and didn't work with 0.
> Implement better GCD algorithm

- .github/workflows/ci.yml
- Makefile
- test/.gitignore
- test/Makefile
- test/Test.juvix
- test/juvix.yaml
This PR is an example showing how we can use the `juvix.yaml` dependency feature to write tests that depend on the current project and an external dependency (in this case providing the quickcheck library).
Run `make test` from the root of the project. It will fetch the quickcheck dependency, compile the Test module and run the tests from the `test/` directory.
> Add Quickcheck testing

- Stdlib/Data/List.juvix
- Stdlib/Data/Product.juvix
- Stdlib/Function.juvix
- test/Makefile
- test/Test.juvix
This PR adds some functions that were defined in the quickcheck project into the standard library.
* `drop : {A : Type} → Nat → List A → List A`
* `snoc : {A : Type} -> List A -> A -> List A`
* `all : {A : Type} -> (A -> Bool) -> List A -> Bool`
* `zipWith : {A : Type} -> {B : Type} -> {C : Type} -> (A -> B -> C) -> List A -> List B -> List C`
* `zip : {A : Type} -> {B : Type} -> List A -> List B -> List (A × B)`
* `mergeSort : {A : Type} → (A → A → Ordering) → List A → List A`
* `quickSort : {A : Type} → (A → A → Ordering) → List A → List A`
In addition this PR adds a curry function to `Stdlib.Data.Product`.
Property tests are added.
The quickcheck library uses both the standard library and copies of these functions and so it must temporarily be pinned to a specific commit that does not …
> Add functions to `Stdlib.Data.List`

- Stdlib/Data/List/Base.juvix
- test/Test.juvix
There was a typo in the definition of `splitAt`:
https://github.com/anoma/juvix-stdlib/blob/c2a327139e9cd166e4e3241f4de192f375a94437/Stdlib/Data/List/Base.juvix#LL79C1-L80C1
So for example:
```
> splitAt 4 (1 :: 2 :: 3 :: 4 :: nil)
1 :: 2 :: nil , 3 :: 4 :: nil
```
This PR fixes `splitAt` and adds tests.
> Fix and test for splitAt function

- Stdlib/Data/Bool.juvix
- Stdlib/Data/Bool/Base.juvix
- Stdlib/Data/Int.juvix
- Stdlib/Data/Int/Base.juvix
- Stdlib/Data/Int/Ord.juvix
- Stdlib/Data/Int/Range.juvix
- Stdlib/Data/List.juvix
- Stdlib/Data/List/Base.juvix
- Stdlib/Data/Maybe.juvix
- Stdlib/Data/Maybe/Base.juvix
- Stdlib/Data/Nat.juvix
- Stdlib/Data/Nat/Base.juvix
- Stdlib/Data/Nat/Gcd.juvix
- Stdlib/Data/Nat/Ord.juvix
- Stdlib/Data/Nat/Range.juvix
- Stdlib/Data/Product.juvix
- Stdlib/Data/Product/Base.juvix
- Stdlib/Data/String.juvix
- Stdlib/Data/String/Base.juvix
- Stdlib/Data/Unit.juvix
- Stdlib/Function.juvix
- Stdlib/System/IO/Bool.juvix
- Stdlib/System/IO/Int.juvix
- Stdlib/System/IO/Nat.juvix
- Stdlib/System/IO/String.juvix
- Stdlib/Trait/Eq.juvix
- Stdlib/Trait/Ord.juvix
- Stdlib/Trait/Show.juvix
anoma/juvix main stdlib submodule currently points to the stdlib`new-function-syntax` branch.
We should:
* Merge `new-functions-syntax` branch  into stdlib main (this PR)
* Update the anoma/juvix stdlib submodule pointer to stdlib main
This PR subsumes https://github.com/anoma/juvix-stdlib/pull/70 and https://github.com/anoma/juvix-stdlib/pull/69
> Update main branch to commit that anoma/juvix main points to

- test/Makefile
juvix-quickcheck v0.6.3 has been updated to support HEAD juvix
> Fix tests failing due to incompatible quickcheck dependency

- Stdlib/Data/Bool/Base.juvix
- Stdlib/Data/Int/Ord.juvix
- Stdlib/Data/List.juvix
- Stdlib/Data/List/Base.juvix
- Stdlib/Data/Nat/Ord.juvix
- Stdlib/Data/Range.juvix
- Stdlib/Extra/Gcd.juvix
- Stdlib/Trait/Ord.juvix
- We rename `if` to `ite` since `if` will become a keyword in https://github.com/anoma/juvix/pull/2852
> Rename `if` to `ite`

- Stdlib/Data/List.juvix
- Stdlib/Data/List/Base.juvix
- Stdlib/Data/Range.juvix
- Stdlib/Data/String/Base.juvix
- Stdlib/Data/Unit.juvix
- Stdlib/Trait.juvix
- Stdlib/Trait/Foldable.juvix
- Stdlib/Trait/Foldable/Monomorphic.juvix
- Stdlib/Trait/Foldable/Polymorphic.juvix
- Closes #110.
This trait is equivalent to the `Foldable` class we all know in Haskell.
```
trait
type Foldable (f : Type -> Type) :=
mkFoldable {-- Combine the elements of the type using the provided function starting with the element in the left-most position.
foldl : {A B : Type} -> (B -> A -> B) -> B -> f A -> B};
```
This trait is similar to the [`MonoFoldable`](https://hackage.haskell.org/package/mono-traversable-1.0.17.0/docs/Data-MonoTraversable.html#t:MonoFoldable) class from the mono-traversable package. This trait is convenient because it can be instantiated by monomorphic (or restricted) types such as `Text`, `Bytes`, `Range N`.
```
trait
type Foldable (container elem : Type) :=
mkFoldable {-- Combine the elements of the type using the provided function starting with the …
```
> Add `Foldable` trait

- Stdlib/Trait/Foldable/Monomorphic.juvix
This change means that `for` and `rfor` will be in scope after `import Stdlib.Prelude open` which is what users expect from tutorials and existing code.
> Export for and rfor from Foldable

- Stdlib/Data/Byte.juvix
- Stdlib/Data/Byte/Base.juvix
- Stdlib/Prelude.juvix
> ⚠️ Depends on:
> * https://github.com/anoma/juvix-stdlib/pull/117
> * https://github.com/anoma/juvix/pull/2918
Adds support for the builtin Byte type introduced in:
* https://github.com/anoma/juvix/pull/2918
> Add support for builtin Byte

- Stdlib/Data/List.juvix
- Stdlib/Data/List/Base.juvix
- Stdlib/Data/Map.juvix
- Stdlib/Data/Set/AVL.juvix
- test/Test.juvix
- test/Test/AVL.juvix
- test/Test/Map.juvix
* Closes #128 
* Closes #129 
* adds more functions to `Stdlib.Set` and `Stdlib.Map`
* improves the implementation of existing functions
* Depends on #127
> Improve Set and Map implementation

- Stdlib/Cairo/Ec.juvix
- Stdlib/Cairo/Poseidon.juvix
- test/Package.juvix
* Adapts to https://github.com/anoma/juvix/pull/3138
> Record updates new syntax
